### ISSUE TITLE
taxonomy table not found

### ISSUE THREAD

**Issue by tbazilegith** [compbiomed/MetaScope#17]
Hello Aubrey / Evan,
I ran onto this issue when downloading target library for Metasope. Any thought about the cause?
> bacterium_rsq <- MetaScope::download_refseq(taxon="bacteria", reference = TRUE, representative = TRUE, compress = TRUE)
Finding bacteria
bacteria is a superkingdom under the Bacteria Superkingdom
Loading the refseq table for bacteria
Error in get_children(taxon, rank_input, data = taxonomy_table) :
  object 'taxonomy_table' not found
Thanks,
TJ

**Comment by aubreyodom** [comment]
Thanks for bringing this to my attention! I'll post an update to the code soon.

**Comment by aubreyodom** [comment]
Hi @tbazilegith , It should be working now. Please let me know if you encounter further issues.
