### ISSUE TITLE
unique_accession_genome_name

### ISSUE THREAD

**Issue by bheimbu** [compbiomed/MetaScope#19]
Hi there,

I'm encountering following error when I ran 

`unique_accession_genome_name <- suppressMessages(
  taxize::genbank2uid(unique_accession_all,
                      batch_size = length(unique_accession_all))) %>%
  vapply(function(x) attr(x, "name"), character(1))
`

`Error: Request-URI Too Long (HTTP 414)`

I'm trying to profile termite microbiomes. I've used _Zootermopsis nevadensis_ as reference genome and Spirochaetia as target reference. So far I've used only one  library, which consists of roughly 7x10⁶ reads.

Any help is highly appreciated,

Bastian

**Comment by aubreyodom** [comment]
Hi Bastian,

Apologies for the late response as I was away on travel.

So, the code that you are using here is taken from a section of the vignette at the very end that takes accession numbers and transforms them to UIDs from a BAM file. However, that is only an applicable step in the vignette as we are evaluating the results of our benchmark. We are taking accessions out of a bam file and turning them into UIDs and then creating a table for the sake of showing what is going on "under the hood."

That step is not applicable to "real life" cases where you don't actually know what is in your sample. In your case, I would skip that code block entirely (and the next one) and go to the `metascope_ID()` step :) The CSV that is output there is the output you're looking for.

I will add a note to the vignette that the step in question is only relevant to the vignette example and can be skipped.

Please let me know if that answers your question!
Brie

**Comment by bheimbu** [comment]
Hi @aubreyodom,

sorry for the late response, I've just realized that the code block is really not applicable to my example ;) anyway, I'd have another question, but I'll open a new issue.

Cheers @bheimbu

**Comment by aubreyodom** [comment]
Not a problem!
