### ISSUE TITLE
No available genome for bacteria - object 'combined_fasta' not found

### ISSUE THREAD

**Issue by tyden46** [compbiomed/MetaScope#9]
Hi, I installed Metascope on April 8, 2021 and I am trying to download all of the refseq bacterial genomes using the `download_refseq()` function. I am running `download_refseq('bacteria', reference = TRUE, representative = TRUE)
` but I am getting the following error on R4.0.3:

No available genome for bacteria - try setting both `representative` and `reference` to TRUE Error in download_refseq("bacteria", reference = TRUE, representative = TRUE) : object 'combined_fasta' not found Execution halted

I have also tried setting representative to FALSE and not including the representative flag at all. Using a capital "B" to write "Bacteria" as an argument to `download_refseq()` works but gives me only 7 genomes.

**Comment by aubreyodom** [comment]
Hi, the issue should be fixed, although the package is still very much under development at the moment as we are working to transition to the bowtie2 aligner. Use at your own risk :)
